dataset: cic_ids
train_batch_size: 128
val_batch_size: 1
test_batch_size: 1
mal_batch_size: 128
dimension: 80
epochs: 4000
model_type:
#   - AE
#   - DAE
#   - SAE
#   - SDAE
#   - SAE1
#   - SDAE1
  # - DualLossAE
  - SupAE
noise_type:
  # - gaussian_noise
  - label_flipping
num_of_poisoned_workers:
  - 0
  # - 10
poisoned_sample_ratio:
  - 1
learning_rate:
  - 0.001
noise_std:
  - 0.001
attack_noise_std:
  - 3
aggregation_type:
  # - attention
  - average
  # - cluster
coef_shrink_ae:
  - 1
threshold_multiplie:
  - 0
num_multi_class_clients:
  # - 0
  # - 5
  # - 10
  - 20
# AE learning_rate 0.001
