dataset: spambase
train_batch_size: 4
val_batch_size: 4
test_batch_size: 1
mal_batch_size: 4
dimension: 57
model_type:
  - DAE
noise_type:
  - gaussian_noise
num_of_poisoned_workers:
  - 0
  - 10
poisoned_sample_ratio:
  - 1
learning_rate:
  - 0.001
  - 0.0001
noise_std:
  - 0.0001
attack_noise_std:
  - 0.1
aggregation_type:
  - attention
  #- average
coef_shrink_ae:
  - 10
# AE learning_rate 0.001
