dataset: unsw
train_batch_size: 128
val_batch_size: 1
test_batch_size: 1
mal_batch_size: 128
dimension: 196
epochs: 1000
model_type:
  #-MultiLossAE
  #MultiZAE
  - SupAE
  # - DualLossAE
  # - AE
  # - DAE
  # - SAE
  # - SDAE
  # - SAE1
  # - SDAE1
noise_type:
  # - gaussian_noise
  - label_flipping
num_of_poisoned_workers:
  - 0
  # - 5
  # - 10
poisoned_sample_ratio:
  - 1
learning_rate:
  - 0.001
noise_std:
  - 0.001
attack_noise_std:
  - 1
aggregation_type:
  # - attention
  - average
  # - cluster
  #- kmean
  #- split
coef_shrink_ae:
  - 1
threshold_multiplier:
  - 0
num_multi_class_clients:
  #- 0
  - 5
  # - 10
  # - 20
by_attack_type: 
  - 1
noniid:
  - True
  # - False
#AE learning_rate 0.001
#DAE learning_rate 0.001 denoising 0.001
# SAE learning_rate 0.0001 coefficient_ae 1
# SDAE learning_rate 0.0001 cofficient_ae 1 noise_std 0.001

